name: ✨ Feature Request
description: Proponi una nuova funzionalità
labels: ["enhancement"]
body:
  - type: textarea
    id: problem
    attributes:
      label: Problema / motivazione
      placeholder: Quale problema risolve questa feature?
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Soluzione proposta
      placeholder: Come vorresti che funzionasse?
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priorità stimata
      options:
        - Alta (blocca funzionalità core)
        - Media (migliora UX)
        - Bassa (nice to have)
