"""add 2fa and trusted devices

Revision ID: 869df0b122df
Revises: 40aa4d02c779
Create Date: 2026-02-24 22:44:57.579882

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '869df0b122df'
down_revision: Union[str, None] = '40aa4d02c779'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trusted_devices',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('device_token', sa.String(length=128), nullable=False),
    sa.Column('device_name', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_seen', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('device_token')
    )
    op.add_column('roles', sa.Column('require_2fa', sa.Boolean(), nullable=True))
    op.execute("UPDATE roles SET require_2fa = FALSE WHERE require_2fa IS NULL")
    op.alter_column('roles', 'require_2fa', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('roles', 'require_2fa')
    op.drop_table('trusted_devices')
    # ### end Alembic commands ###
