"""add_google_auth_field

Revision ID: a3a1cd4468f5
Revises: acce3b2dcf68
Create Date: 2026-02-27 14:30:23.811612

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a3a1cd4468f5'
down_revision: Union[str, None] = 'acce3b2dcf68'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('google_auth', sa.Boolean(), nullable=False, server_default='false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'google_auth')
    # ### end Alembic commands ###
